### ISSUE TITLE
모바일에서 화면 확대되는 버그

### ISSUE THREAD

**Issue by yogjin** [ConceptBe/conceptbe-frontend#40]
### 🐞 Describe

이슈를 적는 현재는 어떤 원인에 의해 버그가 재현되는지 모름

해결방안 참고
https://cjy00n.tistory.com/190 

### 📄 Logs

```shell
.
```

### 🌏 Environment

.

**Comment by semnil5202** [comment]
https://github.com/ConceptBe/conceptbe-frontend/issues/67 해당 이슈에서 해결된 이슈입니다.
