### ISSUE TITLE
내 프로필 - 아이디어, 북마크 글이 많을때 마지막 글이 가려지는 마크업 수정

### ISSUE THREAD

**Issue by yogjin** [ConceptBe/conceptbe-frontend#57]
### 🔨 Describe

<img width="200" alt="image" src="https://github.com/ConceptBe/conceptbe-frontend/assets/33623078/fcd75dad-d5b1-45f8-933f-143168a5237e">

### ✅ Tasks

마크업 수정

**Comment by semnil5202** [comment]
해결된 이슈로 확인되어 클로즈 하겠습니다~
